### ISSUE TITLE
Asterics Zonecontroller gets offset when zooming in within browser 

### ISSUE THREAD

**Issue by riedel** [simonbates/procdraw#86]
Reproduce by zooming in using ctrl + 

Using firefox. Resolved when reloading (f5)

So I guess some inits have to be repeated.

**Comment by simonbates** [comment]
Hi Till. I think this issue should be against nexus-examples?

**Comment by simonbates** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sjruMcKr&#x2F;1-convert-tests-to-google-test"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Convert tests to Google Test</a>
